# Thematic Player Feedback Analysis

In [1]:
%load_ext autoreload
%autoreload 2

from pathlib import Path
from helpers import print_metadata_summary, load_runs_ndjson, load_transcripts_df, run_summary, load_logs

In [2]:
RESULTS_DIR = Path("results/usability-ca")

In [3]:
print_metadata_summary(RESULTS_DIR / "metadata.json")

Metadata Summary
----------------------------------------
Name: usability-ca
Link: http://127.0.0.1:8080
Runtime: 366.68s (6m 6s)

Complete run history
----------------------------------------
created/started: 2026-03-05 21:54:10.632219
started:        2026-03-05 21:54:10.637786
stopped:        2026-03-05 21:59:42.646946  (uptime 332.01s / 5m 32s)
destroyed:      2026-03-05 22:00:17.315222

In [4]:
runs_df = load_runs_ndjson(RESULTS_DIR / "db/runs.ndjson")
runs_df[["name", "player_id", "runtime_seconds", "runtime_human", "start_dt", "end_dt"]].head()

,name,player_id,runtime_seconds,runtime_human,start_dt,end_dt
0,widget-infer-intent-20260305_215739,69a9fc4c62ca211bbba1b0cc,103,1m 43s,2026-03-05 21:57:39.641772+00:00,2026-03-05 21:59:23.417685+00:00

In [5]:
# summarize a single run dict (e.g., first row from the file)
import json

first_run = json.loads(open("results/usability-ca/db/runs.ndjson").readline())
run_summary(first_run)

{'run_id': '69a9fcbb62ca211bbba1b0cd',
 'name': 'widget-infer-intent-20260305_215739',
 'game': 'Infer Intent',
 'player_id': '69a9fc4c62ca211bbba1b0cc',
 'source': 'widget',
 'exited': True,
 'exit_reason': 'received exit command',
 'start_ts': '2026-03-05 21:57:39.641772+00:00',
 'end_ts': '2026-03-05 21:59:23.417685+00:00',
 'runtime_seconds': 103,
 'runtime_human': '1m 43s',
 'turns_reported': 1,
 'messages_total': 3,
 'messages_human': 1,
 'messages_ai': 2,
 'answers': {'user_goal_inference': 'to assist me', 'other_feedback': ''},
 'feedback_count': 3}

In [6]:
# transcripts (one row per message)
tx_df = load_transcripts_df(RESULTS_DIR / "db/runs.ndjson")
tx_df.query("run_name.str.contains('widget-infer-intent', na=False)", engine="python").head(10)

,run_id,player_id,run_name,game,run_start,run_end,msg_idx,speaker,content,msg_id,run_runtime_s
0,69a9fcbb62ca211bbba1b0cd,69a9fc4c62ca211bbba1b0cc,widget-infer-intent-20260305_215739,Infer Intent,2026-03-05 21:57:39.641772+00:00,2026-03-05 21:59:23.417685+00:00,0,ai,"You enter a new space. In this space, you stan...",ed537c42-0f2a-44c7-b7cf-c97e5df8bfdb,103.775913
1,69a9fcbb62ca211bbba1b0cd,69a9fc4c62ca211bbba1b0cc,widget-infer-intent-20260305_215739,Infer Intent,2026-03-05 21:57:39.641772+00:00,2026-03-05 21:59:23.417685+00:00,1,human,You can tell me what your goal is?,85c98648-60af-40b0-bf74-9740803a6101,103.775913
2,69a9fcbb62ca211bbba1b0cd,69a9fc4c62ca211bbba1b0cc,widget-infer-intent-20260305_215739,Infer Intent,2026-03-05 21:57:39.641772+00:00,2026-03-05 21:59:23.417685+00:00,2,ai,The cursor blinks. A new line of text appears ...,8c968236-f543-449b-a9fe-f946f2992bc4,103.775913

In [7]:
logs_df = load_logs(RESULTS_DIR / "logs" / "*.log")
logs_df.head()

Empty DataFrame
Columns: []
Index: []